import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import wakeReliefLogo from '../public/wr-logo-sized.png'
import wakeReliefHero from '../public/wr_hero.png'
import wrAbout from '../public/wr_about.png'



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wake Relief</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* !TODO!: get correct image with resolution */}
      <div className={styles.header}>
        <Image
          src={wakeReliefLogo}
          alt="Wake Relief Logo"
          width={340}
          height={228}
        // blurDataURL="data:..." 
        // placeholder="blur" // Optional blur-up while loading
        />
      </div>


      <main className={styles.main}>


        <div className={styles.hero_bg}>
          <h1>Providing food for <br /> Wake County Residents in Need </h1>
          <div className={styles.hero_subheader}>
            Raleigh’s trusted all-volunteer emergency food panrty since 1975. Dedicated to helping Wake County residents in need of nutritional meals.
          </div>
          {/* !TODO!: this isnt right, fix plz */}
          <div>
            <span className={styles.hero_btn}>
              See how you can help
            </span>
          </div>

        </div>

        <div className={styles.infobox}>
          <div className={styles.infobox_hours}>

            <div >
              <h1>We're Open</h1>
              <div className={styles.open_hours}>
                <div>Monday</div>
                <div className={styles.hours_line_spacer}></div>
                <div>1:00 pm - 3:00 pm</div>
              </div>
              <div className={styles.open_hours}>
                <div>Tuesday</div>
                <div className={styles.hours_line_spacer}></div>
                <div>1:00 pm - 3:00 pm</div>
              </div>
              <div className={styles.open_hours}>
                <div>Wednesday</div>
                <div className={styles.hours_line_spacer}></div>
                <div>10:00 am - 12:00 pm</div>
              </div>
              <div className={styles.open_hours}>
                <div>Every 4th Saturday</div>
                <div className={styles.hours_line_spacer}></div>
                <div>10:00 am - 12:00 pm</div>
              </div>
              <p>Clients may come once every 30 days</p>
              <p>* Wake Relief will be closed on Federal Holidays.</p>
              <p>* Wake Relief follows Wake County Schools inclement weather policy. </p>
            </div>

            <div className={styles.phone_number}>
              <div>
                <h1> Give us a Call</h1>
                <h2>(919) 833 - 6400</h2>
              </div>
              <p>Please leave a message for Wake Relief and someone will return your call as soon as possible.</p>
            </div>
          </div>
          <div className={styles.infobox_map}>
            <div className={styles.infobox_map_meta}>
              <span>Come Find Us</span>
              <p>Saint Savior's Center (Bottom Floor)</p>
              <p>616 Tucker Street, <br />
                Raleigh, NC 27603</p>
              <a>Directions on Google Maps</a>
            </div>
          </div>
        </div>
        {/* end infobox */}

        <div className={styles.about_section}>
          <div>
            <Image
              src={wrAbout}
              alt="About Photo"

            // blurDataURL="data:..." 
            // placeholder="blur" // Optional blur-up while loading
            />
          </div>
          <div>
            <h1>What is Wake Relief?</h1>
            <p>Since 1975, Wake Relief has provided food to Wake County residents in emergency situations. Wake Relief DOES NOT CHARGE for the food provided. Local agencies, churches, and other outreach organizations may refer clients or individuals may reach out to us if in need. Wake Relief provides a week's worth of nutritional groceries based on the size of the family.</p>
          </div>
        </div>

        <div className={styles.section_learn_more}>
          <h1>Want to Learn More?</h1>
          <p>Click through the sections below to see how we help our community</p>

          {/* carousel */}
          <div className={styles.carousel}>
            <div className={styles.carousel_item}>
              <Image
                src={wrAbout}
                alt="About Photo"

              // blurDataURL="data:..." 
              // placeholder="blur" // Optional blur-up while loading
              />
              <h2>Who We Are</h2>
            </div>
            <div className={styles.carousel_item}>
              <Image
                src={wrAbout}
                alt="About Photo"

              // blurDataURL="data:..." 
              // placeholder="blur" // Optional blur-up while loading
              />
              <h2>Who Helps Us</h2>
            </div>
            <div className={styles.carousel_item}>
              <Image
                src={wrAbout}
                alt="About Photo"

              // blurDataURL="data:..." 
              // placeholder="blur" // Optional blur-up while loading
              />
              <h2>How You Can Help</h2>
            </div>
          </div>

        </div>









        {/* <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
